# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_ubuntu:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    runs-on: ${{ matrix.os }}
    env:
      ROCKSPEC: rockspecs/lua-protobuf-scm-1.rockspec
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    steps:
      - name: Install LCov
        run: |
          sudo apt install libperlio-gzip-perl libjson-perl libcapture-tiny-perl libdatetime-perl
          wget "https://github.com/linux-test-project/lcov/releases/download/v1.16/lcov-1.16.tar.gz"
          tar zxf "lcov-1.16.tar.gz"
          cd "lcov-1.16"
          sudo make install
      - uses: actions/checkout@master
      - name: Run Tests
        run: |
          gcc -o test -O test.c --coverage && ./test
      - name: Run LCov
        run: |
          mkdir -p coverage
          lcov -c -d . -o coverage/lcov.info.all
          lcov -r coverage/lcov.info.all '/usr/*' -o coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
  finish:
    needs: test_ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
